name: Github Actions Build

on:
  push:
    branches: ["ci"]
  pull_request:
    branches: ["ci"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install build deps
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential git cmake pkg-config m4 automake pkg-config libtool libdatrie-dev doxygen autoconf-archive
      - name: Autogen
        run: |
          autoreconf -fi
          ./autogen.sh
      - name: Configure
        run: |
          ./configure --disable-dict
      - name: Make
        run: |
          make
      - name: Test
        run: |
          make check
      - name: Install
        run: |
          sudo make install
      - name: Cleanup
        run: |
          make clean
